### ISSUE TITLE
The contents missed in the byte_mlperf/datasets folder

### ISSUE THREAD

**Issue by jackzipu** [bytedance/ByteMLPerf#1]
When run the following command, 

```
python3 launch.py --task albert-torch-fp32 --hardware CPU
```

got several errors, e.g.

```
tar: byte_mlperf/datasets/open_squad: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

```
Traceback (most recent call last):
  File "byte_mlperf/backends/CPU/calculate_cpu_diff.py", line 106, in <module>
    engine.start_engine()
  File "byte_mlperf/backends/CPU/calculate_cpu_diff.py", line 53, in start_engine
    return self.workload_perf(self.workload)
  File "byte_mlperf/backends/CPU/calculate_cpu_diff.py", line 63, in workload_perf
    ds = load_dataset(model_info)
  File "/workspace/public_version/ByteMLPerf/byte_mlperf/core/configs/dataset_store.py", line 39, in load_dataset
    data_loader = importlib.import_module('byte_mlperf.datasets.' +
  File "/workspace/public_version/ByteMLPerf/byte_mlperf/backends/CPU/venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'byte_mlperf.datasets.open_squad.data_loader'
```

After comparing with the local code, found the local code had the following structures of the open_squad folder:

```
.
├── bert
│   ├── accuracy_squad.py
│   ├── evaluate.py
│   └── __pycache__
│       ├── accuracy_squad.cpython-38.pyc
│       └── evaluate.cpython-38.pyc
├── create_squad_data.py
├── data_loader.py
├── dev-v1.1.json
├── eval_features_albert-torch-fp32.pickle
├── packing_utils.py
├── __pycache__
│   ├── create_squad_data.cpython-38.pyc
│   ├── data_loader.cpython-38.pyc
│   ├── packing_utils.cpython-38.pyc
│   └── test_accuracy.cpython-38.pyc
├── test_accuracy.py
└── vocab.txt
```

All the *.py missed in the current `datasets/` folder, and even the `open_squad` folder.

Need add these files to the codes to make it can run.

**Comment by jackzipu** [comment]
And I think the same thing for the following datasets.

```
.
├── open_cail2019
├── open_cifar
├── open_criteo_kaggle
├── open_imagenet
└── open_squad
```

**Comment by JianzheXiao** [comment]
Files have already been added, please check
