### ISSUE TITLE
Debian 12 - LLM inference perf: [Error 24] Too many open files

### ISSUE THREAD

**Issue by tdbyte** [bytedance/ByteMLPerf#121]
When I run the llm infer perf as below:
```
python3 byte_infer_perf/llm_perf/launch.py --hardware_type GPU --task chatglm2-torch-fp16-6b
```
The perf ran for couple of hours before this error
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 206, in benchmark
    raise e
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 201, in benchmark
    bench_accuracy(stub, workload, result_queue)
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 63, in bench_accuracy
    for res in gen_stream_request(
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 44, in gen_stream_request
    for res in stub.StreamingInference(req, wait_for_ready=False):
  File "/root/venv/lib/python3.11/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'OSError'>: [Errno 24] Too many open files: '.tmp_logits/12_1731650346897402661.npy'"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:51000 {created_time:"2024-11-15T05:59:06.897834585+00:00", grpc_status:2, grpc_message:"Unexpected <class \'OSError\'>: [Errno 24] Too many open files: \'.tmp_logits/12_1731650346897402661.npy\'"}"
```

**Comment by suisiyuan** [comment]
Can you provide full log file，just like this

**Comment by tdbyte** [comment]
here is the full log
```
root@instance-20241029-1535:~/ByteMLPerf# python3 byte_infer_perf/llm_perf/launch.py --hardware_type GPU --task chatglm2-torch-fp16-6b
2024-11-15 18:26:54.258 launch.py:333 [INFO]: hardware: GPU
2024-11-15 18:26:54.258 launch.py:334 [INFO]: task: chatglm2-torch-fp16-6b
2024-11-15 18:26:54.258 launch.py:335 [INFO]: host: 127.0.0.1
2024-11-15 18:26:54.258 launch.py:336 [INFO]: port: 51000
model chatglm2-6b already exists, skip downloading model.
baseline chatglm2-6b already exists, skip downloading baseline.
baseline chatglm2-6b already exists, skip extracting baseline.
2024-11-15 18:26:55.700 launch.py:111 [INFO]: start test accuracy.
2024-11-15 18:26:55.700 launch.py:112 [INFO]: using tp_size=1
2024-11-15 18:26:55.700 launch.py:113 [INFO]: using batch_size=1
2024-11-15 18:26:55.700 launch.py:207 [INFO]: Start Server: python3 llm_perf/server/launch_server.py --model_config llm_perf/model_zoo/chatglm2-torch-fp16-6b.json --hardware
_type GPU --tp_size 1 --max_batch_size 1 --port 51000
2024-11-15 18:26:58.468 endpoint.py:38 [INFO]: load tokenizer: llm_perf/model_zoo/sota/chatglm2-6b
2024-11-15 18:26:58.469 endpoint.py:39 [INFO]: **************************************************
2024-11-15 18:26:58.469 endpoint.py:40 [INFO]: bos_token_id: None
2024-11-15 18:26:58.469 endpoint.py:41 [INFO]: eos_token_id: 2
2024-11-15 18:26:58.469 endpoint.py:42 [INFO]: unk_token_id: None
2024-11-15 18:26:58.469 endpoint.py:43 [INFO]: pad_token_id: 0
2024-11-15 18:26:58.469 endpoint.py:44 [INFO]: **************************************************
2024-11-15 18:26:58.471 endpoint.py:55 [INFO]: import setup: <module 'llm_perf.backends.GPU.setup' from '/root/ByteMLPerf/byte_infer_perf/llm_perf/backends/GPU/setup.py'>
2024-11-15 18:26:58.996 mp_engine.py:61 [INFO]: subprocesses created: [3715940]
2024-11-15 18:26:58.996 mp_engine.py:63 [INFO]: waiting for ranks to be ready
<<Begin>> CPU VM State: Used = 70.76 GB, Percent = 3.5% | DEV MEM State(Rank0): Used = 0.0 GB, Reserved = 0.0 GB
<<After build model>> CPU VM State: Used = 70.76 GB, Percent = 3.5% | DEV MEM State(Rank0): Used = 0.0 GB, Reserved = 0.0 GB
loading model:   0%|                                                                                                                                   | 0/7 [00:00<?, ?it/s]
/root/ByteMLPerf/byte_infer_perf/llm_perf/core/ckpt_loader.py:239: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which use
s the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch
/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the funct
ions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via 
`torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open
 an issue on GitHub for any issues related to this experimental feature.
  self.file_cache[file_name] = torch.load(
loading model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.21it/s]
<<After load_weight>> CPU VM State: Used = 82.43 GB, Percent = 4.1% | DEV MEM State(Rank0): Used = 0.0 GB, Reserved = 0.0 GB
<<After model to device>> CPU VM State: Used = 70.29 GB, Percent = 3.5% | DEV MEM State(Rank0): Used = 11.66 GB, Reserved = 11.66 GB
2024-11-15 18:27:13.130 mp_engine.py:67 [INFO]: all ranks are ready and listening, init done
2024-11-15 18:27:13.130 scheduler.py:48 [INFO]: start scheduler thread
2024-11-15 18:27:13.131 endpoint.py:81 [INFO]: warmup prompt: 7年前，我的年龄是我的儿子的6倍，我的儿子今年12岁，我今年多少岁？, config: {'min_new_tokens': 1, 'max_new_tokens': 512, 'top_k': 1, 'get_input_logits': 0}
2024-11-15 18:27:30.800 endpoint.py:99 [INFO]: single warmup response: 根据题意，7年前，我的年龄是我的儿子的6倍，我的儿子今年12岁，我今年多少岁？

首先，我们可以算出7年前，我的儿子年龄为12-7=5岁。

然后，我们可以算出7年前，我的年龄为5×6=30岁。

最后，我们可以算出现在的年龄为30+7=37岁。

因此，我今年37岁。

2024-11-15 18:27:33.269 endpoint.py:104 [INFO]: multiple warmup reponse 0: 根据题意，7年前，我的年龄是我的儿子的6倍，我的儿子今年12岁，我今年多少岁？

首先，我们可以算出7年前，我的儿子年龄为12-7=5岁。

然后，我们可以算出7年前，我的年龄为5×6=30岁。

最后，我们可以算出现在的年龄为30+7=37岁。

因此，我今年37岁。

2024-11-15 18:27:33.274 launch_server.py:69 [INFO]: GRPC Server start at 51000
2024-11-15 18:27:33.275 launch.py:217 [INFO]: Server Ready
2024-11-15 18:27:33.315 reporter.py:122 [INFO]: Update reporter meta: TP=1, BS=1, Inputs=1024
  0%|                                                                                                                                                 | 0/52 [00:08<?, ?it/s]
2024-11-15 18:27:42.049 bench.py:205 [ERROR]: ACCURACY bench_0 error: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'OSError'>: [Errno 24] Too many open files: '.tmp_logits/20_1731695262048425964.npy'"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:51000 {created_time:"2024-11-15T18:27:42.048868674+00:00", grpc_status:2, grpc_message:"Unexpected <class \'OSError\'>: [Errno 24] Too many open files: \'.tmp_logits/20_1731695262048425964.npy\'"}"
>
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 206, in benchmark
    raise e
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 201, in benchmark
    bench_accuracy(stub, workload, result_queue)
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 63, in bench_accuracy
    for res in gen_stream_request(
  File "/root/ByteMLPerf/byte_infer_perf/llm_perf/benchmark/bench.py", line 44, in gen_stream_request
    for res in stub.StreamingInference(req, wait_for_ready=False):
  File "/root/venv/lib/python3.11/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/root/venv/lib/python3.11/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'OSError'>: [Errno 24] Too many open files: '.tmp_logits/20_1731695262048425964.npy'"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:51000 {created_time:"2024-11-15T18:27:42.048868674+00:00", grpc_status:2, grpc_message:"Unexpected <class \'OSError\'>: [Errno 24] Too many open files: \'.tmp_logits/20_1731695262048425964.npy\'"}"
>
```

**Comment by suisiyuan** [comment]
it seems like a system opend files num limit, refer to https://www.howtogeek.com/805629/too-many-open-files-linux/
